
import java.net.InetAddress;
import java.net.UnknownHostException;

/*
 * url2inet.java
 *
 * Created on 24 November 2008, 18:05
 */



/**
 *
 * @author  taha
 */
public class url2inet extends javax.swing.JFrame {

    /** Creates new form url2inet */
    public url2inet() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weServerLabel = new javax.swing.JLabel();
        pcLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        weServerLabel.setBackground(new java.awt.Color(255, 153, 0));
        weServerLabel.setForeground(new java.awt.Color(255, 255, 153));
        weServerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weServerLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        weServerLabel.setOpaque(true);

        pcLabel.setBackground(new java.awt.Color(255, 153, 0));
        pcLabel.setForeground(new java.awt.Color(255, 255, 153));
        pcLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pcLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pcLabel.setOpaque(true);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(weServerLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 69, Short.MAX_VALUE)
                .add(pcLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22))
        );

        layout.linkSize(new java.awt.Component[] {pcLabel, weServerLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(weServerLabel)
                    .add(pcLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {pcLabel, weServerLabel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        weServerLabel.getAccessibleContext().setAccessibleName("webServerLabel");
        pcLabel.getAccessibleContext().setAccessibleName("pcLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //create an object of this class (url2inet)
                url2inet myFrame = new url2inet();
                myFrame.setVisible(true);
                //now run the convert method
                myFrame.convert();
            }
        });
    }

    //Retrieves Innternet (IP) addresses from URL and host names
    public void convert() {
      try {
          InetAddress address1 = InetAddress.getByName("www.ntu.ac.uk");
          InetAddress address2 = InetAddress.getLocalHost();
          weServerLabel.setText("Web Server:  " + address1.getHostAddress());
          pcLabel.setText("My PC:  " + address2.getHostAddress());
        }
        catch (UnknownHostException e) {
          System.out.println("Could not find Departmental Web Server");
        }
      }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pcLabel;
    private javax.swing.JLabel weServerLabel;
    // End of variables declaration//GEN-END:variables

}
